export const data = [
  {
    id: 1,
    img: 'https://www.brggroup.vn/public/media//thumb/sd-golf3-1170x800.jpg',
    name: 'Heden Golf',
    rate: 4.5,
    address: "Abidjan, Côte d'Ivoire",
    review: [],
    photo: [],
    des: 'Set in landscaped gardens overlooking the Ébrié lagoon, this upscale hotel featuring contemporary local art and architectural touches is 3 km from Mosquée de la riviéra and 17 km from Banco National Park.',
    phone: '+225 22 48 26 26',
    checkOutTime: '11pm',
    checkInTime: '12am',
    activity: [],
    food: [],
    review: [],
    roomType: 'Air conditioned',
    price: 127,
    isBooking: false,
  },
  {
    img: 'https://www.brggroup.vn/public/media//thumb/sd-golf3-1170x800.jpg',
    name: 'Heden Golf',
    rate: 4.5,
    address: "Abidjan, Côte d'Ivoire",
    review: [],
    photo: [],
    des: 'Set in landscaped gardens overlooking the Ébrié lagoon, this upscale hotel featuring contemporary local art and architectural touches is 3 km from Mosquée de la riviéra and 17 km from Banco National Park.',
    phone: '+225 22 48 26 26',
    checkOutTime: '11pm',
    checkInTime: '12am',
    activity: [],
    food: [],
    review: [],
    roomType: 'Air conditioned',
    price: 127,
    isBooking: false,
    id: 2,
  },
  {
    img: 'https://www.brggroup.vn/public/media//thumb/sd-golf3-1170x800.jpg',
    name: 'Heden Golf',
    rate: 4.5,
    address: "Abidjan, Côte d'Ivoire",
    review: [],
    photo: [],
    des: 'Set in landscaped gardens overlooking the Ébrié lagoon, this upscale hotel featuring contemporary local art and architectural touches is 3 km from Mosquée de la riviéra and 17 km from Banco National Park.',
    phone: '+225 22 48 26 26',
    checkOutTime: '11pm',
    checkInTime: '12am',
    activity: [],
    food: [],
    review: [],
    roomType: 'Air conditioned',
    price: 127,
    isBooking: false,
    id: 3,
  },
  {
    img: 'https://www.brggroup.vn/public/media//thumb/sd-golf3-1170x800.jpg',
    name: 'Heden Golf',
    rate: 4.5,
    address: "Abidjan, Côte d'Ivoire",
    review: [],
    photo: [],
    des: 'Set in landscaped gardens overlooking the Ébrié lagoon, this upscale hotel featuring contemporary local art and architectural touches is 3 km from Mosquée de la riviéra and 17 km from Banco National Park.',
    phone: '+225 22 48 26 26',
    checkOutTime: '11pm',
    checkInTime: '12am',
    activity: [],
    food: [],
    review: [],
    roomType: 'Air conditioned',
    price: 127,
    isBooking: false,
    id: 4,
  },
  {
    img: 'https://www.brggroup.vn/public/media//thumb/sd-golf3-1170x800.jpg',
    name: 'Heden Golf',
    rate: 4.5,
    address: "Abidjan, Côte d'Ivoire",
    review: [],
    photo: [],
    des: 'Set in landscaped gardens overlooking the Ébrié lagoon, this upscale hotel featuring contemporary local art and architectural touches is 3 km from Mosquée de la riviéra and 17 km from Banco National Park.',
    phone: '+225 22 48 26 26',
    checkOutTime: '11pm',
    checkInTime: '12am',
    activity: [],
    food: [],
    review: [],
    roomType: 'Air conditioned',
    price: 127,
    isBooking: false,
    id: 5,
  },
];
